table Store_Dim
	lineageTag: 2225ea8e-7d4c-413d-b4da-b7049ad4d1ea

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: a8ecd96e-b150-43c7-b8b1-aeb20c8a4323
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_location
		dataType: string
		lineageTag: 870705b7-c6ec-4680-acc2-15c40d8d6207
		summarizeBy: none
		sourceColumn: store_location

		annotation SummarizationSetBy = Automatic

	partition Store_Dim = m
		mode: import
		source =
				let
				    Source = #"Kraken_Koffee_Sales - Copy",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"store_id", "store_location"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

